version: '3'
services:
  node-app:
    restart: unless-stopped
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - 'mongo'
    env_file:
      - .env
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'